
# Copyright 2017, Google, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# [START gae_quickstart_yaml]
runtime: nodejs12
handlers:
  - url: /static/js/(.*)
    static_files: build/static/js/\1
    upload: build/static/js/(.*)
  - url: /static/css/(.*)
    static_files: build/static/css/\1
    upload: build/static/css/(.*)
  - url: /static/media/(.*)
    static_files: build/static/media/\1
    upload: build/static/media/(.*)

  # All URLs ending in .json or .ico are treated as paths to
  # static files in the build/ directory. The URL pattern is a
  # regular expression, with a grouping that is inserted into the
  # path to the file.
  - url: /(.*\.(json|ico))$
    static_files: build/\1
    upload: build/.*\.(json|ico)$

  # All URLs ending in .png are treated as paths to
  # static files in the build/ directory. The URL pattern is a
  # regular expression, with a grouping that is inserted into the
  # path to the file.
  # Notes: doesn't work when it's added to the above (with .json and .ico),
  #        and also needs mime_type: image/png
  - url: /(.*\.png)
    mime_type: image/png
    static_files: build/\1
    upload: build/(.*\.png)
  - url: /api
    script: auto
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /.*
    static_files: build/index.html
    upload: build/index.html

env_variables:
  DB_USER: postgres
  DB_PASS: mfz2gMkiJulF73yi
  DB_NAME: cmpt470db
  CLOUD_SQL_CONNECTION_NAME: cmpt470-proj:northamerica-northeast1:cmpt470db
beta_settings:
  cloud_sql_instances: cmpt470-proj:northamerica-northeast1:cmpt470db
# [END gae_quickstart_yaml]
